# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-30 22:04
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0003_auto_20170830_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.RegexValidator('^[\\u0621-\\u064Aa-zA-Z][\\u0621-\\u064Aa-zA-Z0-9]*([ ]?[\\u0621-\\u064Aa-zA-Z0-9]+)+$', 'Name cannot start with number, should consist of characters.')])),
                ('date', models.DateTimeField(auto_now=True)),
                ('total_amount', models.FloatField()),
                ('paid_amount', models.FloatField(validators=[django.core.validators.MinLengthValidator(0, 'Money cannot be negative!')])),
                ('cashier', models.IntegerField(default=-1)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='pos.Shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='cashier',
        ),
        migrations.RemoveField(
            model_name='item',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
        migrations.AddField(
            model_name='item',
            name='discount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinLengthValidator(0, 'Price cannot be negative!')]),
        ),
        migrations.AddField(
            model_name='item',
            name='receipt',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.Receipt'),
            preserve_default=False,
        ),
    ]
