# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-31 10:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_auto_20170830_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='total_amount',
        ),
        migrations.AlterField(
            model_name='item',
            name='discount',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0, 'Price cannot be negative!'), django.core.validators.MaxValueValidator(1, 'Discount should be less than original price!')]),
        ),
    ]
