# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-31 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_auto_20170831_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
