# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-01 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_auto_20170831_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='change',
            field=models.FloatField(default=0),
        ),
    ]
